---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  HiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hi
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hi
            Method: get

Outputs:
  HelloEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hi/"
